# Generated by Django 5.2.6 on 2025-09-23 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_orderitem_sooicy_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='sooicy_user',
        ),
        migrations.AddField(
            model_name='order',
            name='sooicy_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='back.sooicyuser'),
        ),
    ]
