# Generated by Django 5.2.6 on 2025-10-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_remove_orderitem_sooicy_user_order_sooicy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('scoop-whoop', 'Scoop-Whoop'), ('swirls', 'Swirls'), ('tera-mera', 'Tera-Mera'), ('scoop & sip', 'Scoop & Sip'), ('slay-sundae', 'Slay-Sundae'), ('berry-berry', 'Berry-Berry'), ('rizzler-shake', 'Rizzler-Shake'), ('swirl`s-top', 'Swirl`s-Top'), ('waffles', 'Waffles'), ('sassy-pancakes', 'Sassy-Pancakes')], max_length=20),
        ),
    ]
