# Generated by Django 5.2.6 on 2025-10-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_gluten_free',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_vegan',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_vegetarian',
        ),
        migrations.AddField(
            model_name='product',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='products', to='back.addon'),
        ),
    ]
