# Generated by Django 5.2.6 on 2025-10-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_product_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='order_items', to='back.addon'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='addons_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
